# Script para aplicar migration de coluna 'code' na tabela health_insurances
# Execute este script uma vez para adicionar a coluna ao banco de dados Supabase

Write-Host "========================================"
Write-Host "Aplicando Migration: Adicionar coluna 'code' em health_insurances"
Write-Host "========================================"
Write-Host ""
Write-Host "IMPORTANTE:"
Write-Host "1. Acesse o Supabase Dashboard da sua clínica"
Write-Host "2. Vá para SQL Editor"
Write-Host "3. Cole o SQL abaixo e execute:"
Write-Host ""
Write-Host "------- COPIE E COLE NO SUPABASE SQL EDITOR -------"
Write-Host ""
Write-Host "-- Add code column to health_insurances table"
Write-Host "ALTER TABLE health_insurances"
Write-Host "ADD COLUMN IF NOT EXISTS code VARCHAR(50);"
Write-Host ""
Write-Host "-- Create unique constraint for code per clinic"
Write-Host "ALTER TABLE health_insurances"
Write-Host "ADD CONSTRAINT unique_health_insurance_code_per_clinic UNIQUE(clinic_id, code);"
Write-Host ""
Write-Host "------- FIM DO SQL -------"
Write-Host ""
Write-Host "Após executar o SQL no Supabase, a coluna 'code' estará disponível para usar."
Write-Host ""
